### ISSUE TITLE
First

### ISSUE THREAD

**Issue by rprx** [XTLS/Xray-core#1]
占个位

**Comment by Edwin-Kevin** [comment]
抢楼，举报了（滑稽）

**Comment by ClarkeCheng** [comment]
请问 Xray 用的什么许可证，MPL么？

**Comment by rprx** [comment]
> 
> 
> 请问 Xray 用的什么许可证，MPL么？

MPL

**Comment by meowtech** [comment]
前排留念

**Comment by Oakento** [comment]
留念

**Comment by teddysun** [comment]
过来支持一下。
保持一颗平常心就好。

**Comment by mariokart1992** [comment]
支持大佬

**Comment by kirin10000** [comment]
发生甚么事了？(指XTLS

**Comment by WROIATE** [comment]
看到pre版直接惊了，还在想为啥要去掉，原来是分家了吗

**Comment by kirin10000** [comment]
如果以后二进制文件出来了需要写安装脚本，可以叫我（如果我能用得上的话，因为比我牛逼的大佬多得多

**Comment by twzchi** [comment]
持续关注 xudp ``期待解决 UDP

**Comment by black-head** [comment]
支持大佬

**Comment by Shangbaize-Daoye** [comment]
话说以后vless也和v2ray分家了吗？对于我这用vless但不用xtls的，是否以后需要转到xray上？

**Comment by Oakento** [comment]
> 话说以后vless也和v2ray分家了吗？对于我这用vless但不用xtls的，是否以后需要转到xray上？

不分，不需要

**Comment by kirin10000** [comment]
能不能开个discussion板块，可以随意聊天，不用太拘谨的那种

**Comment by SekiBetu** [comment]
https://github.com/badO1a5A90/v2ray-doc/blob/main/performance_test/Xray/speed_test_2020119.md
向技术低头是幸福的，第一版性能就这么恐怖了

**Comment by qiumzh** [comment]
期待发版！

**Comment by Fhokud** [comment]
支持大佬

**Comment by kery** [comment]
看到v4.33.0的第一条change log直接蒙了，特意去了解了下缘由。支持作者！

**Comment by 2444989513** [comment]
支持大佬

**Comment by isArtJay** [comment]
支持

**Comment by o0HalfLife0o** [comment]
留名支持

**Comment by kousyougi** [comment]
> https://github.com/badO1a5A90/v2ray-doc/blob/main/performance_test/Xray/speed_test_2020119.md
> ![image](https://user-images.githubusercontent.com/38283893/99841802-a7fd8380-2b66-11eb-8b1e-956e1cc40313.png)
> 向技术低头是幸福的，第一版性能就这么恐怖了

请问Xray v1.0.0 要去哪里下载？我是Openwrt X86_64 的平台。

谢谢

**Comment by rm-rf-ccp** [comment]
支持

**Comment by ardayan** [comment]
niubi

**Comment by lmmqxyx404** [comment]
需要人手协助时，大佬可以喊我。
JS比较熟练，go处于初级阶段

**Comment by isArtJay** [comment]
> 需要人手协助时，大佬可以喊我。
> JS比较熟练，go处于初级阶段

需要高级 Go 开发，haha

**Comment by vongoethe** [comment]
> 占个位

Bump support

**Comment by INetbeep** [comment]
支持，期待大佬发版

**Comment by SaigyoujiYuyuko233** [comment]
支持+1 期待

**Comment by Cp0204** [comment]
前排合影

**Comment by mgsqz** [comment]
前排留爪，期待能有xtls with CDN的特性

**Comment by wujians** [comment]
要牛逼了

**Comment by huzy0909** [comment]
期待，支持大佬！！

**Comment by barton0426** [comment]
xtls被剥离了吗？

**Comment by fjweel** [comment]
纯小白，支持一下大佬

**Comment by renweikg1** [comment]
关注！！！

**Comment by muzhi621** [comment]
支持一下

**Comment by LsnmxNB** [comment]
占位先，弱弱问下这是独立出来吗

**Comment by asiaon123** [comment]
可以可以，这是逼我去学GO

**Comment by rurirei** [comment]
seems full compatibility remained as Client does change nothing.

**Comment by 1265578519** [comment]
有没有详细的wiki文档介绍xtls是什么东东，xtls是内置了nginx吗

**Comment by ownlife101** [comment]
**Awesome !!!**

**Comment by tsundcn** [comment]
前排合影，支持大佬！

**Comment by jdnt** [comment]
感谢！！

**Comment by atrandys** [comment]
支持大佬，感谢～

**Comment by tone88** [comment]
大佬NB

**Comment by guanhemeng** [comment]
> 
> 
> 有没有详细的wiki文档介绍xtls是什么东东，xtls是内置了nginx吗，我一直没搞明白这个是什么。。
> 整个互联网就找到XTLS这一篇文章，在说XTLS有多么多么牛逼，吊打其他协议 https://github.com/badO1a5A90/v2ray-doc/blob/main/performance_test/Xray/speed_test_2020119.md

因为v2ray中移除了xtls，所以原文档也已被删除。
简单的来说就是拼接tls避免tls代理的重复加密以提升性能。

**Comment by badO1a5A90** [comment]
> 能不能开个discussion板块，可以随意聊天，不用太拘谨的那种

可以来TG群 https://t.me/projectXray

**Comment by Ardentwheel** [comment]
> https://github.com/badO1a5A90/v2ray-doc/blob/main/performance_test/Xray/speed_test_2020119.md
> ![image](https://user-images.githubusercontent.com/38283893/99841802-a7fd8380-2b66-11eb-8b1e-956e1cc40313.png)
> 向技术低头是幸福的，第一版性能就这么恐怖了

而且在晚间高峰的时候也可以保证较高的速度，现在晚间高峰可以保持5000 Kbps，以前是400 😅

**Comment by vivodi** [comment]
> What happened? Why did XTLS part away with the v2fly team?

### Origin
The original project is called [v2ray](https://github.com/v2ray/v2ray-core).

### Rename
In 2019, the original author of v2ray suddenly disappeared from the Internet. Since other people in the development team did not have complete warehouse permissions, the project was renamed [v2fly](https://github.com/v2fly/v2ray-core) and continued development.

### Breakup
In 2020, [RPRX](https://github.com/RPRX) developed [XTLS protocol](https://github.com/XTLS/Go). He made the code of the XTLS protocol public, but the license is [proprietary code](https://en.wikipedia.org/wiki/Proprietary_software). Because this part of the code does not comply with the packaging rules of Debian packages (Debian packages are only allowed to package code that meets the requirements of [OSI](https://opensource.org/)), the Debian package maintainer of v2ray requested RPRX to use an open source license for the relevant code he developed. However, RPRX does not agree with this change. For related discussions, see https://github.com/XTLS/Go/issues/9. Afterwards, the Debian package maintainer proposed at https://github.com/v2ray/v2ray-core/issues/2789 that v2fly remove the XTLS protocol so that he can continue to provide Debian packages for this project. Afterwards, [Project X Discussion Group](https ://t.me/projectXray) voted to abandon the Debian package or remove the XTLS protocol, and ultimately chose to remove the XTLS protocol.

After v2fly removed the XTLS protocol, RPRX forked the v2fly-core project and established the [Xray-core](https://github.com/XTLS/Xray-core) project that includes the XTLS protocol. Different from the [MIT](https://github.com/v2fly/v2ray-core#MIT-1-ov-file) license used by v2fly, Xray-core uses [MPL 2.0](https://github.com/XTLS/Xray-core?tab=MPL-2.0-1-ov-file#readme) license.

### Conclusion
RPRX's behavior of splitting the project due to his own selfish interests has caused deep harm to the open source community, and he should be permanently nailed to the pillar of shame in the open source community.
