### ISSUE TITLE
quic

### ISSUE THREAD

**Issue by guodie418** [XTLS/Xray-core#1192]
大佬，考不考虑换成quic bbr

**Comment by chika0801** [comment]
没人开工，要用quic直接隔壁hy tuic

**Comment by MrSaeid007** [comment]
Hi @RPRX 

I wanted to report something to you, I hope you read it and it was helpful in Reality protocol. 

The HTTP/2 protocol solves the problem of Head of line Blocking in the Application layer and allows us to send multiple HTTP requests (streams) simultaneously in one connection.  The HTTP/2 protocol uses the TCP protocol, and as a result, the problem of Head of line Blocking still exists in the transmission layer, that is, if we have a network with low quality and if we have packet loss with destination server(IP), Due to the guarantee of the TCP protocol in the order of arrival of the packets, even the packets that were sent earlier, it must wait for the retransmission of the packets that get loss by GFW.

The HTTP/3 protocol uses QUIC (which is designed on the UDP protocol) instead of TCP and QUIC completely solves this problem, so that if we have a request (stream) with packet loss, it causes the rest of the requests cannot be left pending. In theory, the presence of such a protocol on the Iranian network can be very helpful.  Usually, in one of Iran's operators (Irancell), some foreign IPs are intentionally disrupted in such a way that if when we ping with an IP address, we get one packet loss on every 6 requests. (5 successful request and 1 packet loss)

I test Reality with this situation(Dirty IP) and we see updating message in Telegram(can't download video or pictures).
But seems like (Tuic) which on the Quic protocol are working fine with a Dirty IP(one packet loss on every 5 request). And we can see updating message on Telegram(video and pictures loading successfully.

I hope this help you in developing Reality protocol.
If we can use Reality with good SNi via QUIC protocol transmission, I think we can use Dirty IP server as well.
