### ISSUE TITLE
Request to Mark Latest Pre-Release as Stable Due to Limited Functionality of Current Stable Version in Iran | 因为当前稳定版本在伊朗的功能有限，请求将最新的预发布版本标记为稳定版本

### ISSUE THREAD

**Issue by radio-azad-iran** [XTLS/Xray-core#2104]
I have no idea where this program is used other than in Iran and China countries.
I also have no idea about China.
But right now in Iran, nothing works except Reality with uTLS.
Of course, there is also the possibility of Fragmenting with a slight Delay of the ClientHello packet in Tls Handshake, which this program does not support.
To sum up, the latest Stable version, 1.7.5, is useless in Iran at least, and x-ui panels use this version by default, v2rayN uses this version by default, v2rayNG: I guess that's why it doesn't mark its latest pre-release that uses xray core 1.8.1 as stable.
Please mark the latest Pre Release on GitHub as Stable Release.
Thank you.

我不知道这个程序除了在伊朗和中国外，还在哪些其他国家使用。
我对中国也一无所知。
但是现在在伊朗，除了Reality和uTLS外，其他的都无法工作。
当然，也有可能使用TLS握手中的ClientHello数据包进行微小延迟的分片，但这个程序并不支持。
总的来说，最新的稳定版本，即1.7.5，在伊朗至少是无用的，x-ui面板默认使用这个版本，v2rayN默认使用这个版本，至于v2rayNG，我猜这就是它为什么不把使用xray core 1.8.1的最新预发布版本标记为稳定版的原因。
请在GitHub上将最新的预发布版本标记为稳定版。
谢谢。

**Comment by yuhan6665** [comment]
@FranzKafkaYu 同求

**Comment by mega-optimus** [comment]
pre-release means it's not stable.
you can use whatever version you choose.
out of curiosity, what other softwares have you tried?

**Comment by HeXis-YS** [comment]
Although I am not a developer of Xray, I believe this request is inappropriate.
Developers should ensure that they always provide stable and secure software. When a program introduces new features, it has the potential to introduce new vulnerabilities. Especially with software like Xray, these vulnerabilities might lead to a breach of user data or cause them other problems. Given that thousands of people rely on Xray, the damage caused by a single vulnerability would also be unacceptable. The corresponding client software uses stable releases by default for this reason as well.
In this case, developers can mark a version with new features introduced without sufficient testing as a pre-release.
A pre-release means that the developer does not consider the release suitable for use in a generation environment, or for mass adoption by the general user population, until it has been fully tested and marked as a stable release. Until then, users who use this version will need to take the risk for possible vulnerabilities.
Besides, as you mentioned, 1.7.5 is the "default" option for most clients, which means you can choose a non-default option. It's not difficult, you can download them from the Release page.
The developers have their own plans. There's no reason to ask developers to mark a version as stable release that hasn't been extensively tested, just because they're not the default option for the client or can't be downloaded from GooglePlay.

**Comment by radio-azad-iran** [comment]
> Although I am not a developer of Xray, I believe this request is inappropriate. Developers should ensure that they always provide stable and secure software. When a program introduces new features, it has the potential to introduce new vulnerabilities. Especially with software like ...

Thank you very much.
I think a large part of the explanations could have been shortened by providing a Wikipedia link explaining what a pre-release is. Considering that I have used `reality`, the other part of the answer could have been omitted, because it is clear that I am familiar with the process of getting a pre-release.
Instead of investing energy in writing things that didn't create much value, I wish you had noticed that three months have passed since the last stable version. How much more testing is needed? Six months? A year?

In our country, millions of people are directly and indirectly using this product (I repeat the above because it seems not to have been read well). Because Reality is the only remaining option, they are essentially turning to use the pre-release, but with a significantly terrible UX.

Not everyone is technical like you and me. For example, in Windows, the latest version of v2rayN is useless for millions of people from the beginning! After downloading v2rayN, the individual must check the box for pre-release updates in the settings, get the latest xray core from the update menu, and then start using it!

Please, if you know of a specific risk related to version 1.8.1, register a bug for it. And if you or anyone else is going to test this product and provide a report for a certain period of time, announce it. Otherwise, with your vague answers, don't make the situation harder for millions of people who are suffering right now.
Thanks.

@HeXis-YS

**Comment by radio-azad-iran** [comment]
> pre-release means it's not stable. you can use whatever version you choose. out of curiosity, what other softwares have you tried?



> pre-release means it's not stable. you can use whatever version you choose. out of curiosity, what other softwares have you tried?

Thanks for providing a report on the level of internet freedom in different countries. Bear in mind that many websites are filtered in many countries, but in the absence of Deep Packet Inspection, there is the possibility of using regular VPNs readily available from Google Play and Apple Store.

This list is better as it shows countries where the use of xray is more meaningful:
https://en.wikipedia.org/wiki/Deep_packet_inspection

Because this fantastic project is among the few options that can bypass a firewall with DPI feature.

Yes, pre-release doesn't always mean it's not stable. On the contrary, I think xray core 1.8.1 has been much better than version 1.7.5 in terms of server hardware resource consumption and it also performs excellently in bypassing DPI. Right now, hundreds of thousands of people in Iran are using it and with the implementation of the new firewall version in Iran, the rest of the people are also migrating to this latest version.

**Comment by mega-optimus** [comment]
Here's a list of popular proxy softwares in github:
v2ray/xray, trojan-gfw/trojan-go, hysteria, naiveproxy, gost, tuic

**Comment by radio-azad-iran** [comment]
> Here's a list of popular proxy softwares in github: v2ray/xray, trojan-gfw/trojan-go, hysteria, naiveproxy, gost, tuic, shadowsocks

Thank you, I just don't understand the connection of your conversation with the issue.

**Comment by HeXis-YS** [comment]
Basically you're just complaining that there are no out-of-the-box client apps.
With all due respect, developers have their own considerations and plans, and they are not obligated to help users with all their problems, especially non-technical ones. Xray is not there to "save millions of Iranians".
If you know how to use the pre-release version, write a blog, make a video, or pack an out-of-the-box client and share them with people you think need help, rather than asking the developers to make changes.

**Comment by fs8vsx59h** [comment]
Why not you just fork the repo and mark the pre-release as stable for yourself? If the tag can solve your problems .

**Comment by radio-azad-iran** [comment]
> Basically you're just complaining that there are no out-of-the-box client apps. With all due respect, developers have their own considerations and plans, and they are not obligated to help users with all their problems...

We not only forked a project in Iran to solve this problem, but also added a lot of cool features to it, and its client has been added to the [list of clients for this project](https://github.com/XTLS/Xray-core#gui-clients) as well.
The fact that you initially teach me how to download pre-release, or now mention to fork, it's clear that you fundamentally haven't understood the issue!
I don't want to solve my individual problem, because I don't fundamentally have a problem and I'm talking about a large number of people across the big country.
In the absence of extensive advertising mechanisms due to governments' hostility towards circumvention tools and related risks, I don't know if you have any practical experience in the real world or not, but replacing a new software instead of software like v2rayNG and v2ryN which have a lot of tutorials and many ordinary people think only these solutions exist, is not an easy task at all (while from your point of view the matter is as simple as tagging, yes for this project it is that simple, not for a fork, how in your mind is forked project equal to an active project like this one?!)
Please, please, let's focus on this project and please do not suggest solutions outside of this project, I've thought of and implemented much better solutions than your initial ideas to solve this problem.
The question is clear. Is there a specific bug that has not been resolved? Is the Q/A plan being discussed clear? If yes, no problem, we've waited three months, we can wait another year or two. Are we just supposed to wait without any specific reason or plan? This is something I insist on, that enough wait has been done and this pre-release is now battle-tested.

@fs8vsx59h

**Comment by RPRX** [comment]
预计发布 v1.8.2，加一些小功能，修一些小问题
