### ISSUE TITLE
app/dns: failed to retrieve response for storage.googleapis.com. > Post "https://1.1.1.1/dns-query": context canceled

### ISSUE THREAD

**Issue by hczhch** [XTLS/Xray-core#2152]
cat error.log 
2023/05/26 15:21:48 [Warning] core: Xray 1.7.5 started
2023/05/26 17:02:31 [Error] app/dns: failed to retrieve response for storage.googleapis.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/05/26 17:02:31 [Error] app/dns: failed to retrieve response for storage.googleapis.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/05/26 17:02:55 [Error] app/dns: failed to retrieve response for fonts.gstatic.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/05/27 20:57:01 [Error] app/dns: failed to retrieve response for graph.facebook.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/05/27 20:57:01 [Error] app/dns: failed to retrieve response for graph.facebook.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/05/27 21:15:37 [Error] app/dns: failed to retrieve response for graph.facebook.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/05/27 21:15:37 [Error] app/dns: failed to retrieve response for graph.facebook.com. > Post "https://1.1.1.1/dns-query": context canceled

**Comment by hczhch** [comment]
cat /usr/local/etc/xray/config.json
{
  "log": {
    "loglevel": "warning",
    "access": "/home/xx/xray_log/access.log",
    "error": "/home/xx/xray_log/error.log"
  },
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "flow": "xtls-rprx-vision",
            "level": 0,
            "email": "xx@gmail.com"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "alpn": "h2",
            "dest": 8080,
            "xver": 1
          },
          {
            "dest": 8081,
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "alpn": ["h2", "http/1.1"],
          "certificates": [
            {
              "certificateFile": "/home/xx/xray_cert/xray.crt",
              "keyFile": "/home/xx/xray_cert/xray.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}

**Comment by yyiwu** [comment]
首先你的网络是否能访问这个dns网址，我也遇到过但是是因为校园网无法访问，但是换了手机热点就没这个问题

**Comment by hczhch** [comment]
> 首先你的网络是否能访问这个dns网址，我也遇到过但是是因为校园网无法访问，但是换了手机热点就没这个问题
> 
> > First of all, whether your network can access this dns website, I have encountered but because the campus network can not be accessed, but for the phone hotspot there is no such problem
我补充一些说明：
错误信息是 server 端的；
vps 能够正常提供代理功能，暂时没有感觉到这些错误有造成什么影响，不过还是希望能够找到方法消除这个错误；
vps 与 1.1.1.1 的网络是通的

**Comment by hczhch** [comment]
> 首先你的网络是否能访问这个dns网址，我也遇到过但是是因为校园网无法访问，但是换了手机热点就没这个问题
> 
> > First of all, whether your network can access this dns website, I have encountered but because the campus network can not be accessed, but for the phone hotspot there is no such problem

我补充一些说明：
错误信息是 server 端的；
vps 能够正常提供代理功能，暂时没有感觉到这些错误有造成什么影响，不过还是希望能够找到方法消除这个错误；
vps 与 1.1.1.1 的网络是通的

**Comment by yyiwu** [comment]
或者你可以尝试更换dns，例如8.8.8.8

**Comment by chika0801** [comment]
用doh记得类似报错一直有（无论客户端或服务端。
一直没人在意过你日常开网页遇到什么异常现象了吗？

**Comment by hczhch** [comment]
> 



> 或者你可以尝试更换dns，例如8.8.8.8

有尝试过，问题依旧

**Comment by yyiwu** [comment]
> > 
> 
> > 或者你可以尝试更换dns，例如8.8.8.8
> 
> 有尝试过，问题依旧

我猜测是你vps的网络的问题，因为我是因为网络可能不支持dot、doh的访问，你有试过不用dot、doh吗

**Comment by hczhch** [comment]
> 用doh记得类似报错一直有（无论你在客户端或服务端配置中配doh，来反馈的一般是在客户端日志观察到来问比例多些） 一直没人在意过你日常开网页遇到什么异常现象了吗？

日常使用过程中，代理上网都是正常的，没感觉到异常

**Comment by hczhch** [comment]
> > > 
> > 
> > 
> > > 或者你可以尝试更换dns，例如8.8.8.8
> > 
> > 
> > 有尝试过，问题依旧
> 
> 我猜测是你vps的网络的问题，因为我是因为网络可能不支持dot、doh的访问，你有试过不用dot、doh吗

一直都是 doh ，没试过其他方式

**Comment by hczhch** [comment]
> > 首先你的网络是否能访问这个dns网址，我也遇到过但是是因为校园网无法访问，但是换了手机热点就没这个问题
> > > First of all, whether your network can access this dns website, I have encountered but because the campus network can not be accessed, but for the phone hotspot there is no such problem
> 
> 我补充一些说明： 错误信息是 server 端的； vps 能够正常提供代理功能，暂时没有感觉到这些错误有造成什么影响，不过还是希望能够找到方法消除这个错误； vps 与 1.1.1.1 的网络是通的

并不是每次通过代理上网server都输出这个error；仅仅是偶尔出现这个error

**Comment by chika0801** [comment]
如果你没异常。这信息是上古时代就有的，偶尔有人问，都没人管。就这样。

**Comment by WordsWorthLess** [comment]
试试配置一下vps使用1.1.1.1来做dns服务器
```
 sed -i -e 's/nameserver/#nameserver/g;$anameserver 1.1.1.1' /etc/resolv.conf
```

**Comment by hczhch** [comment]
> 试试配置一下vps使用1.1.1.1来做dns服务器
> 
> ```
>  sed -i -e 's/nameserver/#nameserver/g;$anameserver 1.1.1.1' /etc/resolv.conf
> ```

已修改 resolv.conf 并重启 vps ，error还是会出现
```
cat /etc/resolv.conf
# Generated by SolusVM
nameserver 1.1.1.1
nameserver 8.8.8.8

```

**Comment by azzvx** [comment]
1.1.1.1在挺多地区是不可用的，被ISP另做它用了。不过能用1.0.0.1代替。
ping 1.1.1.1只有2ms不到，而且TTL=251，这显然是有问题的。但是ping 1.0.0.1是正常的。
![QQ截图20230530212033](https://github.com/XTLS/Xray-core/assets/1546898/04b95042-9f3c-4f52-a15d-d62caebd84b6)

**Comment by AbasJalali** [comment]
Hello, on the server side, my server log is full of the following errors, which I don't know how they occur and how to fix. I tested with other doh dns servers and these logs exist, but with "1.1.1.1" this error does not exist. Is this error normal? If it is normal, can you please remove this from the xray log because it always comes from this error and makes it harder to find other errors.
2025/02/06 14:01:24 [Error] app/dns: failed to retrieve response for clients3.google.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:02:19 [Error] app/dns: failed to retrieve response for gateway.icloud.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:03:55 [Error] app/dns: failed to retrieve response for www.linuxbabe.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:09:21 [Error] app/dns: failed to retrieve response for us.tv.global.mi.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:13:36 [Error] app/dns: failed to retrieve response for one.one.one.one. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:13:36 [Error] app/dns: failed to retrieve response for one.one.one.one. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:14:35 [Error] app/dns: failed to retrieve response for androidtvlauncherxfe-pa.googleapis.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:14:35 [Error] app/dns: failed to retrieve response for androidtvlauncherxfe-pa.googleapis.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:17:02 [Error] app/dns: failed to retrieve response for cdn.oaistatic.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:17:36 [Error] app/dns: failed to retrieve response for auth.openai.com. > Post "https://1.1.1.3/dns-query": context canceled
2025/02/06 14:17:52 [Error] app/dns: failed to retrieve response for chatgpt.com. > Post "https://1.1.1.3/dns-query": context canceled
