### ISSUE TITLE
Share a testing result

### ISSUE THREAD

**Issue by nuying117** [XTLS/Xray-core#2622]
I am using VLESS+H2+REALITY, sometimes, when the traffic speed becomes unstable, i.e. being detected, I just stop my client and change the value of spiderX, then restart xray client, it may work again, I thought changing spiderX did help, but I was told that theoretically, changing spiderX didn't change anything, since it's not seen "outside",  I did another test, when the traffic became unstable, I just restart xray client, it helped! I try to narrow down the restarting scope, what if I only restart the connection? I tried to modify the codes based on v1.8.4, 
In transport/internet/http/dialer.go, in the Dial function, added an extra option "Close: true" when building the http.Request, it makes xray create a new connection and redo handshake for each request (Yes, I know it does impact performance), testing result shows that it becomes more stable! I can even watch youtube 4k videos smoothly. Before this change, I even can't watch 720p videos in youtube. my testing is still onging, but maybe this just change the traffic pattern/characteristic a little bit which would make the sensorship spend some time to learn.

```
	request := &http.Request{
		Method: httpMethod,
		Host:   httpSettings.getRandomHost(),
		Body:   breader,
		URL: &url.URL{
			Scheme: "https",
			Host:   dest.NetAddr(),
			Path:   httpSettings.getNormalizedPath(),
		},
		Proto:      "HTTP/2",
		ProtoMajor: 2,
		ProtoMinor: 0,
		Header:     httpHeaders,
		Close:      true,   // add this to create a new connection for each http request
	}

```
But this brings me an idea that maybe good to
- provide options for users to configure whether to use a new connection for each request

Additionally, if also considering sometimes, changing SNI would also help, it maybe good to
- provide configuration params for users to config how much TLS/TCP connections to use(instead of only using one connection) for xray client
- for each connection, pick a random SNI from the configured SNIs for TLS

**Comment by us254** [comment]
- **"Provide options for users to configure whether to use a new connection for each request"**: While this might help bypass detection by changing the traffic pattern, it may also raise a red flag for censorship entities. This is because this behavior is not typical for normal web traffic, where connections are often reused for performance reasons. As a result, this could make the traffic more likely to be identified as proxy traffic by advanced detection algorithms.

- **"Provide configuration parameters for users to configure how many TLS/TCP connections to use"**: Allowing multiple concurrent connections might improve performance in some cases but could also lead to more resource consumption on both the client and server sides. Moreover, an unusually high number of concurrent connections from a single client might appear suspicious and attract attention from censorship entities.

- Regarding **Server Name Indication (SNI)**: In a normal web browsing session, the SNI would usually remain consistent for the duration on a specific website. Therefore, frequent changes in SNI might appear abnormal and could be a potential flag for censorship entities.

**Comment by nuying117** [comment]
You are right and thanks for your time, maybe I can only take such approach for fun.

**Comment by MaratLvs** [comment]
Спасибо за подсказку) мне очень пригодились Ваши советы)

**Comment by MaratLvs** [comment]
Thanks for the tip) I found your advice very useful)
