### ISSUE TITLE
Basic xray configuration

### ISSUE THREAD

**Issue by mahmoodn** [XTLS/Xray-core#2710]
Hi
I have created a simple configuration which uses TCP and no TLS, XTLS or Reality is specified. Does that mean the connection is totally unsecure and man-in-the-middle attack is possible? I expect that website and applications connections which use https (for example) have the basic encryption. Is that right?

**Comment by ashad765** [comment]
As you mention your connection to the https website and applications will be fully encrypted. But be aware because vless and trojan don't have any encryption method your ISP and GFW can easily open connection and detect it. You can at last use Shadowsocks or Vmess because they offer simple encryption by uuid, although it's not so safe ( If anyone get access to your uuid, then it can be used to decrypt all your traffic from past and future )

**Comment by yuhan6665** [comment]
answered
