### ISSUE TITLE
Feature request: Balancer to select other outbounds only when the 1st has failed?

### ISSUE THREAD

**Issue by pulsarice** [XTLS/Xray-core#3114]
Hi
I'm looking for a solution to have high availability, But I don't want to select outbounds randomly or based on leastLoad or leastPing.
I want xray to use the first outbound in selector as long as it pings (even if it is slower than the others) and only if the first one has failed, choose the others in selector list.
The outbounds are Portal, so I can't use vnext.

**Comment by yuhan6665** [comment]
yeah you can configure fallbackTag in every balancer

**Comment by RPRX** [comment]
~~这个简单，让 fallback 可以填另一个 balancingRule 的 tag，无限套娃~~

**Comment by RPRX** [comment]
> Kevin: 好，我进来了

**Comment by RPRX** [comment]
~~说实话我感觉中国 GFW 已经躺平了，多监视少封锁，大概是以经济建设为中心了不像前两年喜欢瞎搞，和伊朗 GFW 恰好相反~~

**Comment by Edwin-Kevin** [comment]
@RPRX 原来 R 佬一直在窥屏

**Comment by us254** [comment]
```json
{
  "routing": {
    "balancers": [
      {
        "tag": "fallback-balancer",
        "selector": [
          "portal-1",
          "portal-2",
          "portal-3"
        ],
        "strategy": {
          "type": "latency",
          "fallbackTag": ""
        }
      }
    ],
    "rules": [
      {
        "type": "field",
        "balancerTag": "fallback-balancer",
        "outboundTag": ""
      }
    ]
  }
}
```

**Comment by us254** [comment]
```json
"balancers": [
  {
    "tag": "balancer",
    "selector": [
      "portal-1",
      "portal-2",
      "portal-3" 
    ],
    "strategy": {
      "type": "leastPing"
    },
    "fallbackTag": "portal-2"
  }
],
"observatory": {
  "subjectSelector": [
    "portal-1",
    "portal-2", 
    "portal-3"
  ],
  "probeURL": "https://www.google.com/generate_204",
  "probeInterval": "60s",
  "enableConcurrency": false
}
```

**Comment by SatenRuiko-Lv0** [comment]
> ```json
> "balancers": [ {"tag": "平衡器",
>     "selector": ["portal-1",
>       "portal-2",
>       "portal-3" 
>     ],
>     "strategy": {"type": "皮革"
>     },
>     "fallbackTag": "portal-2"} ],"observatory": {"subjectSelector": ["portal-1",
>     "portal-2", 
>     "portal-3"
>   ],
>   "probeURL": "https://www.google.com/generate_204",
>   "probeInterval": "60s",
>   "enableConcurrency": 虚假的
> }
> ```



> ~这个简单，让 fallback 可以填另一个 balancingRule 的 tag，无限套娃~



> ```json
> "balancers""tag": "",
>     "selector""portal-1",
>       "portal-2",
>       "portal-3" 
>     ],
>     "strategy""type": ""
>     },
>     "fallbackTag": "portal-2""observatory""subjectSelector""portal-1",
>     "portal-2", 
>     "portal-3"
>   ],
>   "probeURL": "https://www.google.com/generate_204",
>   "probeInterval": "60s",
>   "enableConcurrency": 
> }
> ```

大佬，我不知道我理解的对不对。
按照您的写法,leastping轮询第一个节点，发现ping不通，就fallback到第二个节点。
那如果这三个节点里，第一个节点和第二个节点都死了，只有第三个节点是通的。
那岂不是就无限选择这两个坏的节点了吗😭，或者是要经历两个probeInterval之后才能连接到第三个能用的节点。

**Comment by SatenRuiko-Lv0** [comment]
大佬，我不知道我理解的对不对。
按照您的写法,leastping轮询第一个节点，发现ping不通，就fallback到第二个节点。
那如果这三个节点里，第一个节点和第二个节点都死了，只有第三个节点是通的。
那岂不是就无限选择这两个坏的节点了吗😭，或者是要经历两个probeInterval之后才能连接到第三个能用的节点。

**Comment by us254** [comment]
@SatenRuiko-Lv0 



1. The `leastPing` strategy continuously monitors the latency of all outbound connections in the `selector` list (`portal-1`, `portal-2`, `portal-3`).
2. It will always use the outbound connection with the lowest latency, regardless of its position in the `selector` list.
3. If none of the outbound connections in the `selector` list respond, it will fallback to using the `fallbackTag` outbound connection (`portal-2`).
4. There is no infinite loop scenario because the balancer will always attempt to use the outbound connection with the lowest latency, and if none respond, it will fallback to `portal-2`.

you assumed that the balancer would continue to ping `portal-1` and `portal-2` indefinitely, even if `portal-3` is responsive. However, this is not the case because the `leastPing` strategy will always use the outbound connection with the lowest latency, which could be `portal-3` if it is the only responsive node.

**Comment by yuhan6665** [comment]
Use fallbackTag and loopback outbound for now. If someone have time, please put an example in the example repo..

**Comment by Ali-Khazaee** [comment]
https://xtls.github.io/en/config/routing.html#balancerobject

There is no **strategy** in the documentation.

**Comment by Ali-Khazaee** [comment]
@mmmray, thanks

**Comment by FightingForFun** [comment]
If we use the observatory with "probeURL": "https://www.google.com/generate_204", we expect that the response code will be 204 to determine whether the proxy is working or not.

However, in reality... Xray receives a response code of 200 when using "probeURL": "https://www.google.com/generate_204" and considers the server to be working. Although the server provides us with a "placeholder", "web panel", "login and password panel", "own http request data"...

For us, such a server is not working and is not suitable.

Ideally, it would be good to add:
```
{
  "subjectSelector": [
    "outbound"
  ],
  "probeUrl": "https://www.google.com/generate_204",
  "ExpectedResponseCode": 204           // ["200", "301", "400"...]
  "probeInterval": "10s",
  "enableConcurrency": false
}
```

**Comment by yuhan6665** [comment]
@FightingForFun I implemented your suggestion. Can you help with the testing:
https://github.com/XTLS/Xray-core/pull/4062
build:
https://github.com/XTLS/Xray-core/actions/runs/12002771744
(Note that I did not add in observatory but [burstObservatory](https://xtls.github.io/config/observatory.html#pingconfigobject) since it is more extendable)

**Comment by bcngb** [comment]
- [ ] `
