### ISSUE TITLE
Enhancements and Improvement Ideas

### ISSUE THREAD

**Issue by underdog-03** [XTLS/Xray-core#3134]
Hi @RPRX,

I came across some suggestions on @MHSanaei's page[ MHSanaei/3x-ui/issues/1970](https://github.com/MHSanaei/3x-ui/issues/1970) , and it looks like they have some interesting ideas. Do you think any of these would be useful to add or implement in the XRay code?

Apologies for not being proficient in coding, but I thought the ideas were interesting.

Thank you in advance for your time

**Comment by free-the-internet** [comment]
While we are waiting for RPRX, I should add that some of those ideas is hard to implement like pace control without disruption of user's traffic. I also found some counter intuitive ideas, like you introduce intentional anomalies to deter the analysis, but now this anomalies themselves are a sign of the fact that a proxy is in use.
Here, a research concludes that an scheduler should be implement to replicate real application traffic. It says many modifications on the packets are not that effective for their detection approach: [Link](https://ensa.fi/papers/sec24-xue.pdf) However, currently multiplexing seems to be a powerful method to prevent detection.
