### ISSUE TITLE
reality偷自己，反代的风险？

### ISSUE THREAD

**Issue by 404gods** [XTLS/Xray-core#3148]
最近看到好几起因为反代其他网站别认定为网络钓鱼，被域名服务商或VPS服务商封账户封机器的事情。
一直按照chika0801大佬的指南配置了reality偷自己，请问这样部署也属于会被误封的情况吗？
如果存在这种风险，有啥规避的方法？或者单独本机建个伪装站点，那是不是失去了reality的意义？
谢谢大佬

# 反向代理配置 https://www.digitalocean.com/community/tools/nginx
        location / {
            sub_filter                            $proxy_host $host;
            sub_filter_once                       off;

            set $website                          www.lovelive-anime.jp;
            proxy_pass                            https://$website;
            resolver                              1.1.1.1;

**Comment by Fangliding** [comment]
dest是自己没有风险

**Comment by chika0801** [comment]
> 请问这样部署也属于会被误封的情况吗？

不属于

**Comment by modd32** [comment]
> > 请问这样部署也属于会被误封的情况吗？
> 
> 不属于

Sorry to bring this up but once I got a domain suspended by my registra.  

The domain was used for a reverse proxy with the settings you suggested in the gRPC-TLS configuration,  except for the site was Amazon.com, rather than that Bandai site lovelive-anime.jp. Could this be the reason I got suspended?

Would you please elaborate on this?

**Comment by chika0801** [comment]
Is the gRPC-TLS configuration the configuration file in your link?

https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-TLS

> The domain was used for a reverse proxy with the settings you suggested in the gRPC-TLS configuration, except for the site was Amazon.com, rather than that Bandai site lovelive-anime.jp. Could this be the reason I got suspended?

Understanding from your paragraph, are you using a configuration combination with REALITY and then you are filling in the Dest parameter with the URL Amazon.com.

Who are you referring to being suspended by, and is this who is your VPS merchant?

**Comment by chika0801** [comment]
> The VPS vendor sent me a notice and suspended my server. The registra (another company) assigned my domain a "serverHold" code refering to a Netcraft report.

> Huh, the real question I need to bring up probably is like this:
Is that bandai site you suggested going to bing me less trouble than the Amazon site? In terms of reversing proxy.

When you use a combination of forms with REALITY (excluding the steal yourself form of REALITY).

REALITY behaves as a forward to external forms. Let's say the URL used for your server-side DEST parameter is amazon.com, a site that uses cloudflare's CDN service. When a scanner does a scan, it sends a message that doesn't match the corresponding parameter on your server side (public/private key, short ID, etc.), and your VPS forwards the request to amazon.com.

Let's assume that this scanner is a bad guy, and when it gets such a message, it uses your VPS as its relay server to connect into cloudflare's CDN network.

This phenomenon has some similar tutorial videos posted on youtube by someone in the Chinese discussion forum.

So, we are in Xray's TG group when someone sees a Chinese related video or asks a question about it. My advice are, or you buy a domain name application, apply for an SSL certificate, using the form of stealing their own.

For example https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-TLS/nginx.conf#L41 This parameter is to prevent the use of https://github.com/XTLS/ RealiTLScanner scan to your VPS IP and SSL certificate in the domain name, play your VPS is not someone else as REALITY DEST URL role.

So for your question, I think it is the above reason.

Translated with DeepL.com (free version)

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-TLS

This configuration is you have to have your own SSL certificate, your own domain name, is NGINX listening to port 443, due to what is your own, and REALITY has nothing to do with, is not going to cause the above phenomenon.

You have to pay attention to the configuration example with REALITY, all have this problem. Or maybe REALITY itself is this feature, just because no one discusses it in English circles. You may not be aware of it.

Translated with DeepL.com (free version)

**Comment by modd32** [comment]
@chika0801 Glad to check your replies. Your description for the connection between Cloudflare CDN and the Amazon site is sound IMO. That part really rings a bell with me! Thanks!

Still, I am a bit confused. Correct me If I am wrong pls. According to what you've mentioned above, it seems that I don't need to set up a reverse proxy AT ALL since I already have my own domain name and the SSL cert. What I need to do is setting up my own stand-alone website with these two things.

If that's the case, then why is there a section of reverse proxy settings in your Vless-Vision-REALITY (steal oneself) nginx configuration? https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/steal_oneself/nginx.conf Isn't that completely unnecessary? Do I miss sth here?

**Comment by chika0801** [comment]
nginx配置中的反向代理别人的一个网站，只是一个示例，从如果自己熟悉nginx配置，改成你自己本地的内容端口即可。

配置没特殊的意思，我当时写一个反代纯是个人兴趣。

**Comment by chika0801** [comment]
我的ng水平也是入门，帮不上你
